### ISSUE TITLE
Enable language option for Disqus embed

### ISSUE THREAD

**Issue by t18n** [tterb/gatsby-plugin-disqus#10]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Disqus has the option to show the embed in different languages, but the plugin doesn't have `language` in the config props now. 

**Describe alternatives you've considered**
Add the `language` field into `config` prop and follow the following link instruction activate language to change.
https://help.disqus.com/en/articles/1717203-multi-lingual-websites

**Additional context**
I have playaround with the console panel and this makes it work:
- In the browser console where a Disqus embed loaded already, type in this command:
```
window.disqus_config = function() { this.language='vi' } // override default language
window.DISQUS.host._loadEmbed(); // reload embed.
```

**Comment by tterb** [comment]
@turbothinh I've created a PR (#11) that adds the `language` config prop to the package.  
I successfully tested it locally, but it'd be great if you could test it out and confirm that it works in your setup.
