### ISSUE TITLE
FB share feature doesn't show full path to post

### ISSUE THREAD

**Issue by realrubberduckdev** [tterb/gatsby-plugin-disqus#12]
Hello,

I followed the instructions under the usage section of readme.

```
import { Disqus, CommentCount } from 'gatsby-plugin-disqus'

const PostTemplate = () => {
  let disqusConfig = {
    url: `${config.siteUrl+location.pathname}`,
    identifier: post.id,
    title: post.title,
  }
  return (
    <>
      <h1>{post.title}</h1>
      <CommentCount config={disqusConfig} placeholder={'...'} />
      /* Post Contents */
      <Disqus config={disqusConfig} />
    </>
  )
}

export default PostTemplate
```

The `url` variable points at full url of my blog post viz. `blog.com/post1/`.
The `title` has the blog post title with spaces viz. `this is a blog post title`.
I could not figure out how to get the `post.id` so I have set it to the full url of post.
Not sure this is related to the problem, but you may be able to help me out with this information.

The disqus component appears at bottom of my post.
The issue is, clicking on Facebook share doesn't populate the 'comment' section. The url just shows the domain name bit viz `blog.com`, although clicking on it takes me to the post with `#disqus_thread` appended at end of it.
The twitter share seems to work as expected, i.e. a tweet is populated and a disquss url gets appeneded which navigates to blogpost url with `#disqus_thread` appended at end of it.

Do you know how to get it to show the url properly and populate the comment on the FB share?
How did you get post.id ? Is it related to this issue?

**Comment by tterb** [comment]
@realrubberduckdev Okay let me see if I can help resolve your issues:
> Do you know how to get it to show the url properly and populate the comment on the FB share?  

I'm not sure that totally I understand the issue. The Facebook share button is intended to allow you to share the current thread on Facebook, so unless I'm misunderstanding the problem it sounds like this may be the expected behavior. 
Do you have a public repository for this site that I could look at?

> How did you get post.id?  

I would recommend getting the `post.id` directly from the graphql query that you used to get the rest of the post attributes. Though, without being able to see exactly how your site is configured it's difficult to provide more specific advice.

> Is it related to this issue?  

I don't believe these two issues are related.

**Comment by realrubberduckdev** [comment]
Hi @tterb Apologies for the delay in replying.

Here is the branch of [my blog github repo](https://github.com/realrubberduckdev/dp-blog/tree/disqus-integration) where I have been trying to add disqus.

If you want to build it locally try the steps:
```
npm install
gatsby build
gatsby develop
```

That should run the static website at localhost.

The issue I am getting is (check screenshot)
![image](https://user-images.githubusercontent.com/22910832/72672581-127bf980-3a54-11ea-9e79-fc59df38bd60.png)

1. Click share
2. See comment section of share window is empty.
3. See url shows only domain name and not full url to post. Although clicking on it does take me to the right url. (https://www.rubberduckdev.com/flaky-test-detection/#disqus_thread)
I am assuming the correct behaviour is it puts the title of post in the comment section, and shows full url. I could be wrong as I am new to gatsby, react and typescript.

Any help or pointers are welcome :-) 
BTW if you are convinced it is not related to your plugin, we can close this issue.
Thanks a lot.

**Comment by tterb** [comment]
@realrubberduckdev The website looks great!

While I know that this isn't necessarily related to this plugin, I did clone the repo and was able to reproduce the functionality that you described on the `disqus-integration` branch and agree that it would make more sense for the link to display the post title.

I'm going to close out this issue, but I will reach out the to Disqus team on Monday and see if this is a potential issue or the expected functionality.

**Comment by tterb** [comment]
@realrubberduckdev I did some further investigation and found that the data that is displayed in the FB share is actually determined by the metadata tags that are on the given page.

Additional information for how to add these tags can be found [here](https://css-tricks.com/essential-meta-tags-social-media/)

**Comment by realrubberduckdev** [comment]
@tterb Thanks for your help. I will check and try to fix my website. Will let you know how it goes. (In a week or so).
