### ISSUE TITLE
Question about integrating code in blogPost.js

### ISSUE THREAD

**Issue by mauiview** [tterb/gatsby-plugin-disqus#16]
Hello, I am trying to use your plug in and I am having some trouble.  I am a noob so I hope this isn't a nuisance question too you.

I have run the install and modified my gatsby-config.js file.   When I try to add the example plug in code to my blogPost.js template I get errors.  I am sure it is either a function of my placing code in the wrong place or a novice mistake.  Any tips?

Thanks for your time.

**Comment by emmadigital** [comment]
> Hello, I am trying to use your plug in and I am having some trouble. I am a noob so I hope this isn't a nuisance question too you.
> 
> I have run the install and modified my gatsby-config.js file. When I try to add the example plug in code to my blogPost.js template I get errors. I am sure it is either a function of my placing code in the wrong place or a novice mistake. Any tips?
> 
> Thanks for your time.

Hey @mauiview did you managed to integrate disqus plugin ?

**Comment by mauiview** [comment]
Hi,  I have not gotten it to work yet.  I am fumbling through learning.  These are the errors I am getting, I am sure it is because I missed some basic step.  
Brads-MacBook-Pro:gatsby-starter-strata-notion-bw bradleywhite$ import { Disqus, CommentCount } from 'gatsby-plugin-disqus'
bash: import: command not found
Brads-MacBook-Pro:gatsby-starter-strata-notion-bw bradleywhite$ 
Brads-MacBook-Pro:gatsby-starter-strata-notion-bw bradleywhite$ const PostTemplate = () => {
bash: syntax error near unexpected token `('
Brads-MacBook-Pro:gatsby-starter-strata-notion-bw bradleywhite$   let disqusConfig = {
bash: let: =: syntax error: operand expected (error token is "=")
Brads-MacBook-Pro:gatsby-starter-strata-notion-bw bradleywhite$     url: `${config.siteUrl+location.pathname}`,
bash: ${config.siteUrl+location.pathname}: bad substitution
bash: url:: command not found
Brads-MacBook-Pro:gatsby-starter-strata-notion-bw bradleywhite$     identifier: post.id,
bash: identifier:: command not found
Brads-MacBook-Pro:gatsby-starter-strata-notion-bw bradleywhite$     title: post.title,
bash: title:: command not found
Brads-MacBook-Pro:gatsby-starter-strata-notion-bw bradleywhite$   }
bash: syntax error near unexpected token `}'
Brads-MacBook-Pro:gatsby-starter-strata-notion-bw bradleywhite$   return (
bash: syntax error near unexpected token `newline'
Brads-MacBook-Pro:gatsby-starter-strata-notion-bw bradleywhite$     <>
bash: syntax error near unexpected token `newline'
Brads-MacBook-Pro:gatsby-starter-strata-notion-bw bradleywhite$       <h1>{post.title}</h1>
bash: syntax error near unexpected token `newline'
Brads-MacBook-Pro:gatsby-starter-strata-notion-bw bradleywhite$       <CommentCount config={disqusConfig} placeholder={'...'} />
bash: syntax error near unexpected token `newline'
Brads-MacBook-Pro:gatsby-starter-strata-notion-bw bradleywhite$       /* Post Contents */
bash: /Applications: is a directory
Brads-MacBook-Pro:gatsby-starter-strata-notion-bw bradleywhite$       <Disqus config={disqusConfig} />
bash: syntax error near unexpected token `newline'
Brads-MacBook-Pro:gatsby-starter-strata-notion-bw bradleywhite$     </>
bash: syntax error near unexpected token `newline'
Brads-MacBook-Pro:gatsby-starter-strata-notion-bw bradleywhite$   )
bash: syntax error near unexpected token `)'
Brads-MacBook-Pro:gatsby-starter-strata-notion-bw bradleywhite$ }
bash: syntax error near unexpected token `}'
Brads-MacBook-Pro:gatsby-starter-strata-notion-bw bradleywhite$ 
Brads-MacBook-Pro:gatsby-starter-strata-notion-bw bradleywhite$ export default PostTemplate

**Comment by tterb** [comment]
@mauiview Sorry for the delayed response.
From the errors you're seeing it looks like there might be a syntax error somewhere in your implementation. Could you provide an example of your implementation or a link to a public repo that I can use to reproduce the issue?

***Edit:*** I took a look at your `gatsby-starter-strata-notion-bw` repo and I think you'll probably want to have something like this in your `src/templates/blogPost.js`.

```jsx
import React from 'react'
import { graphql } from 'gatsby'
import { Disqus, CommentCount } from'gatsby-plugin-disqus'
import Layout from '../components/layout'
import { parseImageUrl } from 'notabase/src/utils'
export default ({ data }) => {
  const { posts: { id, title, tags, publish_date, html, url, slug, desc, color, cover_image } } = data

  const disqusConfig = {
    url: url,
    identifier: id,
	title: title,
  }
  return (
    <Layout>
      <div id = "main">
        <div>{tags && tags.join(', ')}</div> 
        <h1>{title}</h1>
		<CommentCount config={disqusConfig} placeholder={'...'} />
        <div dangerouslySetInnerHTML={{ __html: html }} />
		<Disqus config={disqusConfig} />
      </div>
    </Layout>
  )
}

export const query = graphql`
  query($slug: String!) {
    posts(slug: { eq: $slug }) {
	  id
      html
      title
      tags
      publish_date
      url
      desc
      color
      cover_image
    }
  }
`
```

**Comment by mauiview** [comment]
Here is where my stuff is.   Let me know if this is what you are asking for.
My Notion Test Site - https://optimistic-davinci-be68c9.netlify.app/blog

https://github.com/mauiview/gatsby-starter-strata-notion/blob/master/gatsby-config.js

I assumed that I needed to add this code to my blogpost.js file, but I don’t understand how to adapt it to my setup.

import { Disqus, CommentCount } from 'gatsby-plugin-disqus'

const PostTemplate = () => {
  let disqusConfig = {
    url: `${config.siteUrl+location.pathname}`,
    identifier: post.id,
    title: post.title,
  }
  return (
    <>
      <h1>{post.title}</h1>
      <CommentCount config={disqusConfig} placeholder={'...'} />
      /* Post Contents */
      <Disqus config={disqusConfig} />
    </>
  )
}

export default PostTemplate


Brad White R.Ph.

**Comment by tterb** [comment]
@mauiview I cloned your repository but am unable to actually get everything running locally because I don't have access to your CMS, but I think the issue you're running into is that you don't have the `config` for the `config.siteUrl` and your `PostTemplate` isn't being passed the `location` parameter.

This isn't a problem, but we'll have to create a pathway for retrieving the current page url for your site within the `PostTemplate`. I would recommend adding a `siteUrl` attribute to your `siteMetadata` in your `gatsby-config.js`. 
```js
siteMetadata: {
  title: "Gatsby Starter - Strata by HTML5 UP",
  author: "Hunter Chang",
  description: "A Gatsby.js Starter based on Strata by HTML5 UP",
  siteUrl: "https://optimistic-davinci-be68c9.netlify.app",
},
``` 

Then you can modify the GraphQL query in your `PostTemplate` to include this data:
(I also added the `id` parameter to the `post` query to retrieve an identifier that can be used in the `disqusConfig`)
```js
export const query = graphql`
  query($slug: String!) {
    site {
      siteMetadata {
        siteUrl
      }
    }
    posts(slug: { eq: $slug }) {
      id,
      html
      title
      tags
      publish_date
      url
      desc
      color
      cover_image
    }
  }
`
```

Then unpack the data like this:
```js
const { 
  site: { siteMetadata: { siteUrl } },
  posts: { id, title, tags, publish_date, html, url, slug, desc, color, cover_image }
} = data
```

So then you can use these values in your `disqusConfig` like this:
```js
const postUrl = `${siteUrl}/blog${slug}`

const disqusConfig = {
  url: postUrl,
  identifier: id,
  title: title,
}
```

Since I don't have access to the CMS and can't troubleshoot this directly, the potential issue to look out for would be checking that the string concatenation for the `postUrl` creates a valid URL (ie: it isn't missing a `/` depending on the contents of the `slug` that is returned from notion).

Let me know if you run into any issues or have any other questions.

**Comment by mauiview** [comment]
Thank you!

Brad White

.

**Comment by tterb** [comment]
@mauiview Were you able to resolve your issue?

**Comment by tterb** [comment]
I'm gonna assume that the issue was resolved since I haven't heard back, but we can reopen this in the future if not.
