### ISSUE TITLE
The plugin doesn't work due to incorrect publish

### ISSUE THREAD

**Issue by pastelsky** [tterb/gatsby-plugin-disqus#2]
Just came across this plugin and noticed that the published npm package is empty. This is probably because - 
1. package.json points to a mainfile `index.js`, which doesn't exist
2. The `lib` folder generated as a result of build is a part of `.npmingore`, hence nothing gets published.

**Comment by tterb** [comment]
@pastelsky Thanks for the update!
This is the first package I've published to npm, so I figured there would inevitably be issues.  
I appreciate the advice, I'll look into this now and publish a working version.

**Comment by tterb** [comment]
@pastelsky The publishing issues should now been fixed in [v1.0.3](https://github.com/tterb/gatsby-plugin-disqus/tree/v1.0.3), but I would appreciate your confirmation.
