### ISSUE TITLE
Add SSO Integration

### ISSUE THREAD

**Issue by tomrndom** [tterb/gatsby-plugin-disqus#25]
**Is your feature request related to a problem? Please describe.**
I need to use the SSO integration in a site, but it seems that config object doesn't have the required props, `remote_auth_s3` and `public_key`

**Describe the solution you'd like**
Right now I'm using the [disqus-react](https://github.com/disqus/disqus-react/) implementation to solve this and it seems like that adding those props into the config should be enough. I could open a PR to add those props.

**Comment by tterb** [comment]
@tomrndom Thanks for the suggestion, I'll try to get a PR up for this this week!

**Comment by tterb** [comment]
@tomrndom I've put up a PR (#26) with the additional SSO parameters, but I don't actually have a SSO-enabled site to test with locally. 
Could you try running it with your SSO integration to confirm that it provides the expected behavior?

**Comment by tomrndom** [comment]
Sure. I'll test it ASAP

**Comment by tomrndom** [comment]
Great! I just tested it and it's working.

**Comment by tterb** [comment]
@tomrndom Awesome! I'll merge that PR and publish a new release to npm shortly.
