### ISSUE TITLE
How to get comment count to display in heading meta?

### ISSUE THREAD

**Issue by i-bsd** [tterb/gatsby-plugin-disqus#3]
Is there a way to do this?

It seems you can do it with `disqus-react` package but not sure about `gatsby-plugin-disqus`.

**Comment by tterb** [comment]
@i-bsd I actually started working on a `CommentCount` component to do just that a couple days ago.   
 I've been pretty busy with work this week, but I'm hoping it will be added and published by this weekend.

***Edit:*** Progress on this pushed to [`add-commentcount-component`](https://github.com/tterb/gatsby-plugin-disqus/tree/add-commentcount-component) branch

**Comment by i-bsd** [comment]
Thanks a lot! Looking forward to trying it.
