### ISSUE TITLE
React 17

### ISSUE THREAD

**Issue by tysoncadenhead** [tterb/gatsby-plugin-disqus#53]
I'm trying to install the latest version of this plugin using React 17, but there appears to be a peer dependency on React 16. I can see in this repo that the React peer dependency has been bumped to 17, but it doesn't seem to have a new version available in NPM. Am I missing something?

**Comment by tterb** [comment]
@tysoncadenhead The React version in the `package.json` has been updated since the last version of the package was published. I'll try to get the new version published to NPM in the next few of days.

**Comment by tterb** [comment]
@tysoncadenhead Just published [`v1.2.3`](https://www.npmjs.com/package/gatsby-plugin-disqus) (which includes the React v17 support) to NPM.
