### ISSUE TITLE
disqus transforms url like text to HTML <a> tag

### ISSUE THREAD

**Issue by zhuscat** [tterb/gatsby-plugin-disqus#60]
For Example, here is my article's HTML content:

```html
<p>foo.example.com</p>
```

After I use `Disqus` component on my website, the HTML content is transformed to:

```html
<p>
  <a class="vglnk" href="http://foo.example.com" rel="nofollow"><span>foo</span><span>.</span><span>example</span><span>.</span><span>com</span></a>
</p>
```

Is this expected?

Look forward to your reply.

**Comment by tterb** [comment]
@zhuscat I don't believe that's the expected functionality, but you should be able to disable affiliate links using the "Affiliate links" settings for your website at https://disqus.com/admin/settings/advanced, which should prevent this from happening.
