### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by styfrombrest** [tterb/gatsby-plugin-disqus#68]
Hi!
First of all, I'd like to say thanks for great plugin which allows add disqus comments in a really simple way.
The only problem I faced with is lack of typings. Can you please add typescript support for the plugin?
Thanks in advance!

**Comment by tterb** [comment]
Yeah, I'll try to work on adding type definitions in the next week or so 👍

**Comment by styfrombrest** [comment]
Thanks a lot!

**Comment by tterb** [comment]
@styfrombrest I just put up a PR with type definitions and then realized that they were already added in #35. 
Are you using `v1.2.4` of the plugin?

**Edit:** It looks like the type-definitions weren't being used because they weren't configured in the `package.json` 🤦

**Comment by tterb** [comment]
Tracked down the issue after publishing the changes in `v1.2.5` to the definitions not being included in the `build` script.
I just published `v1.2.6` which should fix all the issues 👍

**Comment by styfrombrest** [comment]
@tterb Sorry for the slow reply, just want to confirm that 1.2.6 works good. Thanks!

**Comment by tterb** [comment]
@styfrombrest Thanks for confirming!
